# Generated by Django 5.0.6 on 2024-05-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_city_country_gallery_placecategories_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='hotels_gallery', to='traveler.gallery'),
        ),
        migrations.AlterField(
            model_name='places',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='places_hotels', to='traveler.hotels'),
        ),
        migrations.AlterField(
            model_name='places',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='places_gallery', to='traveler.gallery'),
        ),
    ]
