# Generated by Django 5.0.6 on 2024-05-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0003_alter_hotels_images_alter_places_hotels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video',
        ),
    ]
