# Generated by Django 5.0.6 on 2024-05-16 15:58

import traveler.helps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0004_remove_gallery_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default=1, upload_to=traveler.helps.SaveMediafile.save_about_us_media),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travels',
            name='image',
            field=models.ImageField(default=1, upload_to=traveler.helps.SaveMediafile.save_travel_media),
            preserve_default=False,
        ),
    ]
