# Generated by Django 5.0.6 on 2024-05-16 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0005_aboutus_image_travels_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='hotels',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='placecategories',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='travelcategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='travels',
            options={'ordering': ('id',)},
        ),
        migrations.AddIndex(
            model_name='aboutus',
            index=models.Index(fields=['id'], name='traveler_ab_id_fe612e_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['id'], name='traveler_ad_id_e53cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['id'], name='traveler_ci_id_abbe47_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['id'], name='traveler_co_id_d276ac_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['id'], name='traveler_ga_id_0b8279_idx'),
        ),
        migrations.AddIndex(
            model_name='hotels',
            index=models.Index(fields=['id'], name='traveler_ho_id_40aac9_idx'),
        ),
        migrations.AddIndex(
            model_name='placecategories',
            index=models.Index(fields=['id'], name='traveler_pl_id_014bff_idx'),
        ),
        migrations.AddIndex(
            model_name='places',
            index=models.Index(fields=['id'], name='traveler_pl_id_fad999_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['id'], name='traveler_te_id_f9aab7_idx'),
        ),
        migrations.AddIndex(
            model_name='travelcategory',
            index=models.Index(fields=['id'], name='traveler_tr_id_9d6cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='travels',
            index=models.Index(fields=['id'], name='traveler_tr_id_b17640_idx'),
        ),
    ]
