# Generated by Django 5.0.6 on 2024-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0007_hotels_service_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='return_day',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
