# Generated by Django 5.0.6 on 2024-05-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0008_alter_travels_return_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='about_us',
        ),
    ]
