# Generated by Django 5.0.6 on 2024-05-16 18:37

import traveler.helps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0010_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcategory',
            name='image',
            field=models.ImageField(default=1, upload_to=traveler.helps.SaveMediafile.save_tour_category_media),
            preserve_default=False,
        ),
    ]
